- broker/broker.go
- broker/client.go
Heya! 
I've found that `topicsMgr.Subscribers(...)` can leads to unpredictable subs listing in high concurrent scenario. Seems that a simple lock sort that out. Please have a look if you can think of a better way.
Regards!
> simple fix

- broker/broker.go
- broker/config.go
- go.mod
- go.sum
Closes #77 
That way you can create your own plugins, e.g.
```
type specialAuth struct {
...
}
func (auth *specialAuth) CheckACL(action, clientID, username, ip, topic string) bool {
...
}
func (auth *specialAuth) CheckConnect(clientID, username, password string) bool {
...
}
myAuth := &specialAuth { ... }
myConfig := &broker.Config {
Plugin: {
Auth: myAuth,
},
}
```
> Configure plugins by struct instead of by name

- broker/broker.go
By default, the websocket library checks whether there is an `Origin` header in the very first HTTP request. This is pointless unless you check the contents of this header. It is even in the way when the requests do not come from browsers. (I used the mqtt client from hivemq- https://hivemq.github.io/mqtt-cli/ for testing. It has a websockets mode.)
While I was at this, I also figured that the code uses the global variable `http.DefaultServeMux`. This could be problematic when the broker is included into a larger server as library. Instead, a local mux is created for serving websocket requests.
> do not expect "Origin" header for websocket connections

- broker/client.go
According to the MQTT-3.1.1 spec: "A Keep Alive value of zero (0) has the effect of turning off the keep alive mechanism." (section 3.1.2.10). This can also be useful for local connections as it reduces the surface for implementation errors.
> only set a read deadline when the keep-alive value is positive

- broker/comm.go
- go.mod
- go.sum
[satori/go.uuid](https://github.com/satori/go.uuid) is no longer maintained. Snyk is reporting a [vulnerability](https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488) where UUIDs are not random (https://github.com/satori/go.uuid/issues/73). This PR replaces `sartori/go.uuid` with [google/uuid](https://github.com/google/uuid) and also resolves an issue I got when building `master`:
```
broker/comm.go:117:10: assignment mismatch: 2 variables but uuid.NewV4 returns 1 values
```
Fixes #88
> Replace satori/go.uuid with google/uuid

- plugins/auth/authfile/acl.go
- plugins/auth/authfile/acl_test.go
I wanted to create an extension to the authfile plugin to load config from a reader instead from a file. While testing it I realized that the aclAuth function CheckACL uses parameter order ... username, ip ... where the checkTopicAuth function uses ... ip, username ...
The result is that the included sample config is not correctly working when writing a test against it.
> Bugfix - authfile plugin did wrongly use username as IP and IP as username in ACL checks

- broker/client.go
If `ControlPacket` panics, then `WriterPacket` will never unlock the lock. This PR lets it use defer to unlock the lock.
> Use defer to unlock in WriterPacket()

- .gitignore
- broker/client.go
Issue #104 
This PR implements the following rules:
Reference: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf
_The character data in a UTF-8 encoded string MUST be well-formed UTF-8 as defined by the Unicode
specification [Unicode] and restated in RFC 3629 [RFC3629]. In particular this data MUST NOT include
encodings of code points between U+D800 and U+DFFF. If a Server or Client receives a Control Packet
containing ill-formed UTF-8 it MUST close the Network Connection [MQTT-1.5.3-1]._
_A UTF-8 encoded string MUST NOT include an encoding of the null character U+0000. If a receiver
(Server or Client) receives a Control Packet containing U+0000 it MUST close the Network
Connection [MQTT-1.5.3-2]._
> Packet fields validation

- broker/client.go
During runtime we encountered an error with a fast disconnecting client (I assume that's the problem) which resulted in a nil pointer error:
```
{"level":"warn","timestamp":"2021-03-17T14:41:10.988+0100","logger":"broker","caller":"broker/broker.go:348","msg":"client exist, close old...","clientID":"api.hornet-0.testnet.chrysalis2.com"}
{"level":"error","timestamp":"2021-03-17T14:41:10.988+0100","logger":"broker","caller":"broker/client.go:174","msg":"read packet error: ","error":"read tcp 172.18.0.3:1883->20.190.228.100:1156: use of closed network connection","ClientID":"api.hornet-0.testnet.chrysalis2.com"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13e82d7]
goroutine 166999 [running]: …
```
> Adds nil check for subscription/topic-mngr at client Close()

- broker/client.go
If receive a client disconnect pack:
1.Then need to break the read packet loop before next loop start, to avoid a IO error.
2.To clear will msg, according to MQTT 3.1.1: "The Will Message MUST be published when the Network Connection is subsequently closed **unless** the Will Message has been deleted by the Server on receipt of a **DISCONNECT Packet**".
> client disconnect fixed

- .github/workflows/go.yml
Fix #138 
Drop the support for Golang 1.14, support golang 1.15+
> Drop the support for Golang 1.14

- broker/client.go
- broker/comm.go
- this race condition occurs when a client is disconnected or when hmq checks
if client still alive (#153)
Signed-off-by: Lucas Vieira <lucas.engen.cc@gmail.com>
> fix: :bug: fixes race condition

- Dockerfile
This PR modifies the Dockerfile to use `ENTRYPOINT` so that command line args can get passed into container when executed.
For example:
```
docker build -t hmq:latest .
docker run hmq:latest -p 1883
```
> docker: use ENTRYPOINT so command line args can get passed into container when executed

- README.md
The link  https://github.com/surgemq/surgemq seems to be another repo and this seems to be the current one https://github.com/zentures/surgemq
> Update surgemq repository link

- broker/bridge.go
- broker/client.go
- broker/info.go
- plugins/bridge/bridge.go
- plugins/bridge/csvlog.go
- plugins/bridge/kafka.go
- plugins/bridge/mock.go
allow bridgemq to cost the message
add bool return value on `Publish` method to allow bridge mq to cost the message
```
type BridgeMQ interface {
Publish(e *Elements) (bool, error)
}
```
If the bridgeMq returns true, we won't send msg to it's subscriber
> allow bridge mq cost msg

- pool/fixpool.go
```
func (p *WorkerPool) dispatch() {
for i := 0; i < p.maxWorkers; i++ {
p.taskQueue[i] = make(chan func(), 1024)
go startWorker(p.taskQueue[i])
}
}
```
since function *dispatch* execute *startWorker* by goroutine, there is no need for *startWorker* to use goroutine inside.
> rm a redundant creation of goroutines

- Dockerfile
Hi!
The Dockerfile placed at "Dockerfile" contains the best practice violation [DL3006](https://github.com/hadolint/hadolint/wiki/DL3006) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3006 occurs when the image tag for the base image is missing.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, we use a heuristic approach that selects the most probable version tag for the given base image. In detail, it selects the most recent image tag which corresponds to the same image digest that currently corresponds to the "latest" tag, used by default when pulling the image from DockerHub if a specific image tag is …
> Fix for Dockerfile smell DL3006

- .gitignore
- broker/broker.go
- broker/client.go
- broker/http.go
During a temporary service re-hydration, this allows the recovering service to:
1.) Sub to /connections for all incoming connections then
2.) Get a list of all connections that exist rn.
This is useful for rebuilding caches and if any of your edge-workers need to be restarted, they can. It also allows for you not to have a 100% coupling in Redis or any other MQ stream. There are still no routes for the MQ streams to get all conns on connect, when we migrate to this we will add in this support as well.
Also cleaned up some routing patters in Gin, added in some constants to make it cleaner to add a lot of REST routes later.
Also added in new type "resp" to push down the values over json, use the omitempty tag to tell encoding/json to ignore this field.
Pro tip: if you have a struct nested …
> Added in GET /connections to update restarting node

- broker/broker.go
- broker/client.go
- broker/http.go
Runtime issue wasn't previously handled when the WillTopic was null, Go's compiler wouldn't care but it would throw a runtime error if there was no Last Will set. We should consider adding in a unit test system to properly catch this next time.
@chowyu12 can you please upstream this and tag a new release like v1.5.2 with the hot fix?
> HOTFIX | Fixed pubMsg when WillTopic is null

- broker/broker.go
- broker/config.go
- broker/pipe_socket_darwin.go
- broker/pipe_socket_linux.go
- broker/pipe_socket_windows.go
- go.mod
- go.sum
I added pipe socket conditions for different systems and used the open source project npipe, which nicely encapsulates the operation of the Windows pipe and returns a net.Conn type connection, compatible with hmq, making it very convenient for Windows users like us. I noticed that in the last committed Unix socket communication, the name UnixSocket is not standard, it should be unixSocket. I'm terribly sorry.
> fix(broker):Added windows pipe socket communication, compatible with other systems #199

- broker/broker.go
I need to fix the file removal function of unixsocket, if not removed, it will cause the sock file to be occupied every time you start，We sincerely hope that the author can re-issue a new version for our use
> fix(broker):Added file removal for unix sock communication #203

- broker/config.go
- logger/logger.go
When the project was officially used for debugging, the debug and info levels were too low, resulting in too much log information being printed, which affected the operation effect of the project. I hope to give users more opportunities to choose log levels. The bool type used in the code is somewhat limited for more log choices, so I changed it to string type. And added the error log level switch
> fix(hmq):Increased the log level of error #205
