fhmq/hmq

- plugins/bridge/kafka.go
> fix: topics used but not make

- broker/client.go
fix ipv6 address / port splitting
> fix ipv6 addresses

- broker/lib/topics/memtopics.go
Signed-off-by: Liu Qing <winglq@gmail.com>
> update retained message even if it's already there

- broker/client.go
Fixes a nil pointer exception.
> do not try to set remoteIP for websocket connections

- broker/client.go
- broker/info.go
Fix issue here: https://github.com/fhmq/hmq/issues/76
> fix fail in cluster deploy

- broker/client.go
- broker/comm.go
- go.mod
> Feature qos1&qos2

- broker/lib/topics/memtopics.go
> op: smatch low performance code

- broker/lib/topics/memtopics.go
Reverts fhmq/hmq#102
find bug for smatch 'repeat query'
> Revert "op: smatch low performance code"

- broker/broker.go
When starting hmq immediately after booting, the IP address specified in the
--host flag (e.g. --host=10.0.0.217) might not be configured yet.
Without this commit, hmq would try to listen, give up, and then just hang.
With this commit, hmq automatically recovers.
> retry listening indefinitely

- broker/client.go
- broker/comm.go
Details about the crash and the reason for the change can be found : https://github.com/turtletramp/hmq/issues/2
It is hard to reproduce (only happened once in about 2 month of use by 2 developers during their daily work). So the change is based on the error data + reading the existing code.
Solution: I added a sync.RWMutex to control concurrent access to the client.inflight map
> panic - fatal error: concurrent map writes

- .github/workflows/go.yml
This is a pipeline to build the project on microsoft windows, linux ubuntu and macos using go versions 1.14 and 1.15
> Add a build pipeline

- broker/broker.go
According to MQTT 3.1.1 [Connect Return code] :
**If a server sends a CONNACK packet containing a non-zero return code it MUST then close the Network Connection [MQTT-3.2.2-5].**
[http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html](url)
> fix: close the connection after send connection refused connack packet.

- broker/broker.go
- broker/client.go
It can occasionally happen that the maps are accessed concurrently.
This PR fixes the panics "concurrent map read and map write".
> Use locks around client maps

- .gitignore
- conf/hmq.config
- plugins/bridge/CSVLog.md
- plugins/bridge/bridge.go
- plugins/bridge/csvlog.go
- plugins/bridge/csvlog_test.go
This is a PR for the addition of a CSV logging plugin.
Comments / feedback extremely welcome
> First Commit

- broker/broker.go
- broker/config.go
- broker/lib/sessions/session.go
Rmoeve unnecessary type convert, these variable are original string.
> Rmoeve unnecessary type convert

- .gitignore
- broker/broker.go
- broker/http.go
> Allow Broker DisConnect connections by ClientId

- broker/broker.go
Close conn when read connect packet error
> Close conn when read connect packet error

- broker/broker.go
- broker/comm.go
- broker/info.go
> [cleanup] delete comment out code

- broker/broker.go
- broker/client.go
Allow publish message by clientId
> Allow publish message by clientId

- broker/broker.go
This fixes a nil pointer exception which was introduced with #146
> Fix nil pointer exception in addr logs

- broker/client.go
- plugins/bridge/csvlog.go
- fix a misleading code annotation
- remove a dead variable
> fix a misleading code annotation

- broker/broker.go
The `websocket.Conn` type does not return any value with the `remoteAddr()` function. It stores the information in the field `wsConn.Request().RemoteAddr`
> fix: :bug: fixes nil pointer dereference

- .github/workflows/go.yml
> create： go.yml

- broker/broker.go
There are lots of  unclosing _conns_ inside function _handleConnection_.
> fix conn.Close() in function handleConnection

- broker/broker.go
- broker/config.go
feat(hmq):Provide handler StartUnixSocketClientListening used to handle the Unix communications
> fix(broker): Added support for unix socket communication #50
